### ISSUE TITLE
End of CN support

### ISSUE THREAD

**Issue by Aireil** [Aireil/FFLogsViewer#13]
Hey,

I am wondering if any of you would be willing to take the CN support in a fork and distribute a CN supported version.
I am grateful for the help you provided to make this current version CN-compatible, but I will not be able to support both versions at the same time in the same repo.
There are big client changes in 6.1 and probably in the future, making it a bit of a nightmare to maintain for me.
A full rewrite of the plugin is also planned, linking even more the plugin with the client and I cannot test anything on the CN client.

For these reasons, I will end the CN support in this version with the full 6.1 update of the plugin. I am really sorry about that.

@NukoOoOoOoO @LittleNightmare

**Comment by LittleNightmare** [comment]
got it. although i don't have the skills to do it myself, i think i could relases a version until CN server been updated to 6.1

**Comment by NukoOoOoOoO** [comment]
Understandable, already pull upstream commits for my fork, now I just need to play around with installer stuff, thank you for your work :^)

**Comment by Aireil** [comment]
The 2.0.0.0 version completely drops compatibility.
I see that you set up a repo, so I will link here if someone comes across this issue, thank you!
https://github.com/NukoOoOoOoO/DalamudPlugins
