### ISSUE TITLE
After Extreme 3 released, the FFLogs Viewer screen is cutting the bottom of the screen.

### ISSUE THREAD

**Issue by imgidedin** [Aireil/FFLogsViewer#14]
![image](https://user-images.githubusercontent.com/19570528/163684917-9819ebcd-6e63-419f-8ebc-9cc558258d15.png)

**Comment by Aireil** [comment]
My guess would be due to the Dalamud style or scaling. I have made good progress with a rewrite that will (hopefully) remove all these sizing issues.

**Comment by Aireil** [comment]
Should be fixed in 2.0.0.0, please open an new issue if there are still issues.
