### ISSUE TITLE
Add tippy integration

### ISSUE THREAD

**Issue by kalilistic** [Aireil/FFLogsViewer#15]
https://gist.github.com/kalilistic/89cc1ddb8b8b583b590b97e7b86e2138

**Comment by Aireil** [comment]
Maybe later, but not that soon after the rewrite!

**Comment by kalilistic** [comment]
Please this ticket open so I can track your progress.

**Comment by MKhayle** [comment]
please open this ticket very important

**Comment by Aireil** [comment]
I'm waiting for a PR from the Tippy dev.

**Comment by MKhayle** [comment]
@tippy dev please pr

**Comment by MKhayle** [comment]
pls use ipc for tippy

**Comment by Aireil** [comment]
Because no PR from the Tippy dev, so not happening.

**Comment by kalilistic** [comment]
why was this closed

**Comment by MKhayle** [comment]
Because no PR from the Tippy dev, so not happening.

**Comment by kalilistic** [comment]
![image](https://user-images.githubusercontent.com/35899782/221369593-337ea471-e325-4e2f-986e-33a060df5c31.png)

**Comment by MKhayle** [comment]
tippy dev bad
