### ISSUE TITLE
[Feature Request] Add All-Star Points

### ISSUE THREAD

**Issue by gamescom15** [Aireil/FFLogsViewer#17]
Something like a header showing the all-star points, although i am not sure how to implement it so that it's understandable in the UI without adding too much text around it.

I was thinking something like this:
![fflogs_asp](https://user-images.githubusercontent.com/10470023/164451525-6f55ac10-29d1-4679-b1ba-7f058c46e521.png)
 
But i can see how you could easily confuse the headers for Kills and the ASP rank. Any ideas?

**Comment by Aireil** [comment]
I wanted to add ASP somehow, but as it's split based on jobs + split again on partitions, I just gave up the idea for now.
I'm not too versed in that metric, so I'm not exactly sure what people would want to see in general.

**Comment by malcolm-smith** [comment]
Seeing current rank would be a great addition to the table
![image](https://user-images.githubusercontent.com/42984447/164943871-6b3196cf-f2b2-4e17-9819-1dc78af66e8a.png)
Easy to see if someone's highest parse is historically high or presently high. For example, this p4s parse is historically pink but has the current rank of orange.

![image](https://user-images.githubusercontent.com/42984447/164943852-0ad778b8-e774-46d8-aa03-a586699d8900.png)
Maybe adding another row to this menu for 'rank' and showing the colour of that rank would be a good start. Would also have to change dynamically like the parse percentile when changing between rdps, adps, and ndps.

**Comment by Aireil** [comment]
If the partition doesn't matter, I can add points and rank stats per encounter easily.
For ranks, wouldn't it better to have this %? Although I can just add both options I guess.
![g7TWIPm](https://user-images.githubusercontent.com/33433913/164944735-21295244-a587-46df-a6ac-a04ad0c947c9.png)

While I'm at it, are people interested in detailed percentiles? e.g., if the API gives me 87.9735, I just display 87, same as ff logs profiles. But I could just have a setting to display with more precision, if that's desirable.

**Comment by malcolm-smith** [comment]
I personally like the rank more than the current percentile, since that is most similar to what is shown on the actual fflogs page. As far as detailed percentiles, fflogs seems to round to 1 decimal place for most things, like perf averages.
![image](https://user-images.githubusercontent.com/42984447/164949793-061d5941-acea-46cf-b1ce-4e1a90a998ad.png)

**Comment by malcolm-smith** [comment]
Also just an idea for the interface for handling partitions, you could add another dropdown menu here beside 'rdps'.
![image](https://user-images.githubusercontent.com/42984447/164950408-d9454a86-2f19-40a1-96f5-b956b754b5a6.png)
Could have an 'all', '6.0' and '6.1' option

**Comment by Aireil** [comment]
I'm not willing to handle partitions, it's something that is zone based and overall just annoying.
If you want to see in details a breakdown per partition, I'd suggest clicking the "Viewing..." to open the FF Logs page in browser.

I'll add all stars points / rank / rank percent stats per encounter though.

**Comment by Aireil** [comment]
> I'll add all stars points / rank / rank percent stats per encounter though.

Available in 2.0.3.0.

**Comment by gamescom15** [comment]
Thanks!
