### ISSUE TITLE
Context menu info

### ISSUE THREAD

**Issue by xPumaa** [Aireil/FFLogsViewer#21]
Since the context menus are back, the information can be removed in the settings

**Comment by Aireil** [comment]
Fixed in the next update, thank you.

**Comment by ichi-obi** [comment]
Are they back though? Folks over at goat place discord server say that they are still disabled. Am I missing something?

**Comment by Aireil** [comment]
I'm not using those provided with Dalamud, hence why it doesn't matter that Dalamud's are disabled.
See #19 for more info.
