### ISSUE TITLE
FFLogs viewer doesn't show logs properly

### ISSUE THREAD

**Issue by frukbachers** [Aireil/FFLogsViewer#22]
I cleared UWU once in SB, but it doesn't reflect in the viewer properly.

Due to me wanting my ingame identity to be private, I can't provide logs, but i guarantee you that I have cleared UWU during SB. Changing the layout so it shows Stormblood Ultimtes doesn't reflect properly.

Using a random player, for example "Rap Breon" from Tonberry (JP) who cleared it during Stormblood, this is how it reflects in the ingame window:

https://i.imgur.com/AD64tgn.png

Unclear if it has anything to do with API call limits.

**Comment by Aireil** [comment]
Hey, this is due to the metric. rDPS is not supported by these encounters, I've added a warning for it in the latest version, thank you for the report.

**Comment by frukbachers** [comment]
Thank you, this was quickly resolved. Godspeed to you sir.
