### ISSUE TITLE
Context menu gone?

### ISSUE THREAD

**Issue by TheGreatAce** [Aireil/FFLogsViewer#23]
![image](https://user-images.githubusercontent.com/61169595/169616090-d8d0d779-8755-4522-b419-57e46476e037.png)
For some reason, FFLogs doesn't show up on the context menu anymore. Is this a bug?

**Comment by Aireil** [comment]
Are you sure you did not use /xlui? If so, please screenshot your Misc tab in the config.

**Comment by TheGreatAce** [comment]
That command doesn't seem to exist for me, and also here:
![image](https://user-images.githubusercontent.com/61169595/169626595-dd4f12dc-dc8e-4d5c-b95c-e758900ce81d.png)

**Comment by Aireil** [comment]
I found the issue, Dalamud got rollbacked and it broke a feature added in the latest version.
I pushed a fix for it in the version 2.0.4.4 that is deploying right now, thank you for the report!
(FYI I deleted your comment just to not show your API key 👍)

**Comment by TheGreatAce** [comment]
(I realized shortly after I posted it haha), but thank you so much!
