### ISSUE TITLE
[Feature Request] Check everyones specific boss.

### ISSUE THREAD

**Issue by Battler624** [Aireil/FFLogsViewer#26]
Instead of checking a person, we check everyone in the party for a specific boss.

**Comment by Aireil** [comment]
I've been thinking on how to have a proper display for the party for a while, but haven't really found something satisfactory yet in terms of UI.

**Comment by Battler624** [comment]
Do the opposite of what is currently shown, the top right button where you choose party members becomes the boss chooser.

And the list instead of being bosses, it becomes party members | server | logs (for that specific boss)

**Comment by Aireil** [comment]
This is now available in 2.1.0.0 with party view, your specific idea is the stat layout version.

![3iiE51P](https://user-images.githubusercontent.com/33433913/217425478-9261b2de-33f8-4d5c-b6ac-f0c62f8394e4.png)
