### ISSUE TITLE
[Issue] No character found from clipboard 

### ISSUE THREAD

**Issue by sauronshotdogs** [Aireil/FFLogsViewer#27]
after the new update, any search will return "No character found from clipboard" Doesn't open in browser anymore either

**Comment by Aireil** [comment]
I'll take a look, but there hasn't been any update in more than a month.
Can you look in /xllog if you see red text and screenshot what it says?

**Comment by sauronshotdogs** [comment]
Oh, thanks for the instant reply
Will try

**Comment by sauronshotdogs** [comment]
Yup, all working again. Thanks a ton!
