### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by bluepaperss** [Aireil/FFLogsViewer#29]
Plugin broke recently so I tried reinstalling it.
This showed up and I wasn't sure if it was a me problem or a plugin issue.
Did both restarts and reinstalls just to be safe but it just didn't happen.
![image](https://user-images.githubusercontent.com/125661093/219647391-d5bff3c3-5a23-4b28-bb66-4231e41ea988.png)

Thanks in advance!

**Comment by Aireil** [comment]
What do you mean by broke?
Please upload the dalamud.log file that is in `%appdata%/XIVLauncher` (it contains your Windows username, feel free to replace it or DM me the log on Discord).

**Comment by bluepaperss** [comment]
It just wouldn't install from the plugin window for some reason. The client ID was invalid no matter what I did so I tried reinstalling the plugin but it just wouldn't. 😭
If you don't mind me contacting you personally on Discord, please do let me know your discord!

**Comment by Aireil** [comment]
Sure, Aireil#8310.

**Comment by Aireil** [comment]
It was a VPN issue, closing.
