### ISSUE TITLE
Add a way to quickly open Party view

### ISSUE THREAD

**Issue by jjspace** [Aireil/FFLogsViewer#31]
I find that a huge majority of the time that I type `/fflogs` to open the window I want to see party view not a specific person. it'd be great if I could type `/fflogs party` and get that view or even better just have a setting to make it default to the party view unless a player is specified.

**Comment by Aireil** [comment]
Added `/fflogs party` and `/fflogs p` to open and refresh the party state as well as a default view setting.
Although `/fflogs` without argument is just a simple toggle of the window, so if it was previously changed to single view, it will bring that up again.
Also made it refresh the party state when switching to party view, so it's less clicks if you were already on single view.

**Comment by jjspace** [comment]
Works like a charm, thank you!
