### ISSUE TITLE
Doesn't always clear empty party slots

### ISSUE THREAD

**Issue by jjspace** [Aireil/FFLogsViewer#32]
I've been finding that the party view often doesn't clear spots for members that aren't in the party anymore which can be really confusing trying to scan it. I usually notice it after doing a bunch of PF stuff so maybe it's something with switching groups too much? I noticed it started after the update that added the `/fflogs p` shortcut for #31 

![2023-09-05_23-56-59](https://github.com/Aireil/FFLogsViewer/assets/8007967/900487ed-e318-43d0-b1e8-6c6d13dead9c)

**Comment by Aireil** [comment]
Just to make sure, are you using the refresh button once they're gone?

**Comment by jjspace** [comment]
Yes, using `/fflogs p` and clicking the refresh button both appear to refresh party members but don't remove the missing people.

I think this happens most after I've been in a PF group and viewed the party view for that group then left it and joined another. That's when it shows people from the previous group.

**Comment by Aireil** [comment]
Fixed, someone changed the behavior of some Dalamud internals without warning, thanks!
