### ISSUE TITLE
Implement Tomestone.gg to show Prog % if not cleared

### ISSUE THREAD

**Issue by ScarVite** [Aireil/FFLogsViewer#37]
Tomestone.gg is a new FFXIV Website released and partially developed by Khira (FFlogs dev).
It shows ur Current Prog Point on Fights Based on Public Logs, and ur best pull %.
Alot of ppl Have been using this site to check how far ppl have been into prog to fight progliars.
Could be an Idea, if the Implementation isnt to hard, to show the Progpoint if no logged clear has been found/Display the Found Achievement based on tomestone.

This is how it looks if ur progging TOP atm f.e.
![image](https://github.com/Aireil/FFLogsViewer/assets/43887376/ca1b8bf4-3464-4e25-aa97-6c0d18db065c)

**Comment by Aireil** [comment]
I've added said link in the latest version of the plugin:
![button](https://github.com/Aireil/FFLogsViewer/assets/33433913/297dd37d-e499-425e-9df9-0a5d75282c9a)
I'm closing this issue for now, but I'm keeping an eye on the potential API that would allow a better integration.
