### ISSUE TITLE
Show ndps as default for parses from stormblood

### ISSUE THREAD

**Issue by frukbachers** [Aireil/FFLogsViewer#39]
Less of an issue, more of a suggestion.

I personally have my layout set up to view historical ultimate parses (among others):

![grafik](https://github.com/Aireil/FFLogsViewer/assets/75330029/71b604de-0ccb-486f-bd74-207bd1aa1b32)

I'd like to keep rDPS as default metric to view, but I have to swith each time I want to check the ultimate parses from stormblood.

Would it be possible to set a default metric inside the layout that overrides the top selection? 
![grafik](https://github.com/Aireil/FFLogsViewer/assets/75330029/3854197b-b4fb-4575-8e87-c799f7b4fc7a)

**Comment by Aireil** [comment]
Unfortunately, the way it's currently setup would make this a little bit annoying to implement and I don't feel like it would be worse the hassle :/.

**Comment by Aireil** [comment]
I could maybe add a way to overwrite just dps for specific zones, but the UI wouldn't match the correct loaded metric using the default (if set to rDPS).
Which I guess wouldn't really matter for those zones as rDPS is never valid 🤔 .

**Comment by frukbachers** [comment]
Alright, thanks for letting me know your thoughts. Closing issue then, and have a great day.

**Comment by Aireil** [comment]
Now available in the latest update, just force aDPS (it's aDPS, not nDPS) on those encounters and it should work as you expected to (hopefully 👁️).

**Comment by frukbachers** [comment]
I just now noticed the change and wanted to say many thanks. You're right, I actually meant aDPS instead of nDPS and since it only applies to Parses from Stormblood (at least on my end), one could just make a note like this in the encounter alias.

![grafik](https://github.com/Aireil/FFLogsViewer/assets/75330029/4788f580-bc40-4fda-bc26-4ef70b304a35)

Either way, thank you very much for your consideration.
