### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by lokicorgi1** [Aireil/FFLogsViewer#42]
Can you make it so that it displays clears from Stormblood and Shadowbringers? It's to make it easier to show I'm not lying about clears.

**Comment by Aireil** [comment]
You can change the layout in the settings to have it however you want it.
If it's about ultimates, unfortunately, the way the zones are split on FF Logs makes it quite expensive to fetch all of them. Hence why it's only DT + EW on the default layout.

**Comment by lokicorgi1** [comment]
oh damn. well I hope there's a way to make it cheaper in the future.

**Comment by Aireil** [comment]
I just mean in terms of FF Logs API point btw, not real money. It just limits the number of players you can fetch over an hour.
Closing the issue as you can just edit your layout if you want that, but I don't want to do it in the default layout with how the FF Logs API is setup right now.
