### ISSUE TITLE
Colums squished together

### ISSUE THREAD

**Issue by Blondella** [Aireil/FFLogsViewer#44]
Not exactly sure how this happened, it just one day borked like this & I haven't been able to get it fixed since. 
![4TMbhtg](https://github.com/user-attachments/assets/0349ed06-063d-4cf0-8b3b-4f4201504450)

**Comment by Aireil** [comment]
Oh yeah, something's broken with the stat layout, oops. I guess so few people use it that I never knew! hehe
I'll fix it in the next update.

**Comment by Aireil** [comment]
Should be fixed in 2.1.7.7 that is deploying right now, should be available in the next few minutes 👍.
