### ISSUE TITLE
This Client is NOT valid

### ISSUE THREAD

**Issue by CoreXI7** [Aireil/FFLogsViewer#45]
It was working just fine then overnight I'm getting a client not valid error. I have tried to make a new API key a few times but it keeps on giving me "This client is NOT valid" did it break or am I doing something wrong?
![Screenshot_2](https://github.com/user-attachments/assets/eee48933-9ac7-40e0-8014-ba6668ec61c4)
![Screenshot_1](https://github.com/user-attachments/assets/09bf3734-bf74-47d0-9f2e-5edcacd35549)

**Comment by Aireil** [comment]
Look at what's in the log (/xllog) when you try adding it, there should be an error in red.

**Comment by CoreXI7** [comment]
Hmm, thats odd. I went to go create another client and it worked this time. lmao thank you for your support Aireil. I'm going to chalk it up to user error hehe I must have been doing something wrong repeatedly yesterday.

I hope you have a great day and thank you for making this plugin. I love it!

**Comment by Aireil** [comment]
No worries, it was probably a connection issue to FF Logs' servers.

**Comment by CoreXI7** [comment]
So it happened again and I found out why. seems like my VPN is causing issues it doesn't work when its on but if I turn it off FFLogsViewer works

**Comment by CoreXI7** [comment]
opened it by accident, sorry.
