### ISSUE TITLE
Feature Request Prog Precent %

### ISSUE THREAD

**Issue by IrulanSB** [Aireil/FFLogsViewer#48]
Hello amazing dev, I am requesting two feautres.
1. Add a prog % 
![{8E759162-F494-4CD4-8C70-E272A18823B4}](https://github.com/user-attachments/assets/0b4b74cf-6699-4f89-8430-91634501c889)
2. Add a cleared quick glance all time.
![{099378A2-A730-451C-8176-B0FF5286903D}](https://github.com/user-attachments/assets/390dc279-f8e7-4ae0-84db-58daece9d7fc)

I often have to open tome stone to see these things, and I would love to see them in the plugin.
Anyway happy holidays!

**Comment by Aireil** [comment]
Hey, I've actually got this working on a branch for a while, but my main issue is this would probably reduce Tomestone's traffic, which Kihra wasn't too hot about I believe.
I could ask again now that Tomestone has gain more popularity, but yeah...

**Comment by IrulanSB** [comment]
I see, thank you for the reply.
Keep being awesome!
