### ISSUE TITLE
Feature request: Alliance Raids support (Chaotic)

### ISSUE THREAD

**Issue by bit-S0** [Aireil/FFLogsViewer#49]
Right now if I go to party list and use the plugin to check logs for other alliances, it just displays logs for my current party (alliance) 

It would be nice to have it show other alliances' logs

mainly to check how many people cleared for the bonus (joining kill parties just to see 24 people have cleared kinda sucks tbh) but it could also just be used to log/prog check if people wanted for chaotic 

thank you

**Comment by Aireil** [comment]
Well good news, there's an alliance swap button in the party view since the one of the last updates :).

**Comment by Aireil** [comment]
You may not see it now as it's only displayed when you're in an alliance, but it looks like this.
![image](https://github.com/user-attachments/assets/b3866d38-aa66-409b-ad15-cc04d49846c2)

**Comment by bit-S0** [comment]
Sick, I didn't notice it before but yeah it's pretty handy
Much appreciated for all of your work, thanks

**Comment by Aireil** [comment]
🫡
