### ISSUE TITLE
Right-click -> Search FF Logs only working on self

### ISSUE THREAD

**Issue by gamescom15** [Aireil/FFLogsViewer#5]
The Right-Click feature appears to only work when clicking myself in the party list or when targeting myself and then right-clicking the target bar.

When set to "Open in browser":
* the site is only opened when you yourself are the target

When "Open in browser" is off:
* The window is only opened/refreshed when you yourself are the target

Streamer mode works fine when the window is already open.

Searching for people manually using the "target" button in the fflogs window also works fine, so it does not appear to be a problem with the client ID/Secret.

As an additional note that might help you, while it does not work in the party list or player search, both features appear to work when using the FC member list, which is quite odd.

**Comment by gamescom15** [comment]
After some experimenting with enabling/disabling plugins, the conflict seems to stem from the combination with the context menu additions in the PlayerTrack plugin. I assume that plugin is using the same library as well.

Disabling and then reenabling that plugin fixes it until the next game restart. My assumption is that the order that it loads the plugins in has an effect on it. Is there a way to change that load order as a band-aid fix?

I assume you're refering to XivCommon, which unfortunately does not appear have an issue page, but maybe i just can't find it.

**Comment by Aireil** [comment]
You probably moved the context menu item position in PlayerTrack settings, hence why the same bug happens.
The XivCommon dev is aware, it's just annoying to fix and there's little I can do except don't move the default position.

**Comment by gamescom15** [comment]
You're right, i must have changed that when i initially installed it. For now, i'll just leave it in the default position and wait for xivcommon to update. 

Thanks for the quick response!

**Comment by Aireil** [comment]
Nothing that I can do but to wait, so I'm closing this.
