### ISSUE TITLE
Logs Viwer display option request

### ISSUE THREAD

**Issue by torakiti2017** [Aireil/FFLogsViewer#8]
1. Display the Logs of the selected player.
2. Not displayed during combat.
Can these options be added?

Regarding 1.
Currently, if you right-click to select a player and display the Viewer, the Viewer will remain displayed, so you will need to close it. It is helpful if the Viewer is hidden if no player is selected.

I'm sorry if all these requests are already possible.

**Comment by Aireil** [comment]
I will add the second feature to the next update. Not really interested in the first feature, sorry.

**Comment by Aireil** [comment]
2. has been added to the new 1.5.6.1 version.

**Comment by torakiti2017** [comment]
Thank you for your support!
