### ISSUE TITLE
after update v 1.5.6.0 fflogs window wont pop up

### ISSUE THREAD

**Issue by patsy158** [Aireil/FFLogsViewer#9]
the only way to bring up the fflogs window is to type /fflogs. is there any way to fix it?

**Comment by imachocolate1** [comment]
type /fflogs in your chat and it'll show up again

**Comment by patsy158** [comment]
so clicking on the search fflogs button function won't work anymore?

**Comment by Aireil** [comment]
It should work, can you give me an example of a character name that doesn't work?

**Comment by patsy158** [comment]
Kage Suta for example. I tried uninstall and reinstall still right click on search ffligs doesnt work anymore. Only way to bring up the window is to type /fflogs

**Comment by Aireil** [comment]
Oh, the context menu. I see what you mean, let me fix that.

**Comment by patsy158** [comment]
Okidoki thank you

**Comment by Aireil** [comment]
Should work again in 1.5.6.1, thanks for the report 👍.
